# Generated by Django 3.1.3 on 2020-12-15 19:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('acd_lst', '0005_auto_20201208_1431'),
    ]

    operations = [
        migrations.CreateModel(
            name='Cargoemprego',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('codcargo', models.CharField(max_length=10)),
                ('codgrupocargo', models.CharField(max_length=10)),
                ('nomecargo', models.CharField(max_length=200)),
                ('nivel', models.CharField(max_length=10)),
            ],
        ),
        migrations.CreateModel(
            name='Orgaosiape',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('codigo', models.CharField(max_length=10)),
                ('nome', models.CharField(max_length=200)),
            ],
        ),
        migrations.CreateModel(
            name='Rubricas',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('codigorubrica', models.CharField(max_length=10)),
                ('nomerubrica', models.CharField(max_length=200)),
            ],
        ),
        migrations.DeleteModel(
            name='InfoCadastroFicha',
        ),
        migrations.DeleteModel(
            name='InfoFinanceiraFicha',
        ),
    ]
