# Generated by Django 3.1.3 on 2021-02-24 22:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('acd_lst', '0006_auto_20201215_1614'),
    ]

    operations = [
        migrations.CreateModel(
            name='GratPontuacao',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nomegrat', models.CharField(max_length=10, verbose_name='Gratificação')),
                ('pontuacao', models.DecimalField(decimal_places=2, max_digits=5, verbose_name='Pontuação')),
                ('datainicio', models.CharField(max_length=10, verbose_name='Data de início')),
                ('datafinal', models.CharField(max_length=10, verbose_name='Data final')),
            ],
        ),
        migrations.CreateModel(
            name='GratValorPonto',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nomegrat', models.CharField(max_length=10, verbose_name='Gratificação')),
                ('datainicio', models.CharField(max_length=10, verbose_name='Data de início')),
                ('datafinal', models.CharField(max_length=10, verbose_name='Data final')),
                ('nivel', models.CharField(max_length=3, verbose_name='Nível')),
                ('classe', models.CharField(max_length=1, verbose_name='Classe')),
                ('padrao', models.CharField(max_length=1, verbose_name='Padrão')),
                ('valorponto', models.DecimalField(decimal_places=2, max_digits=8, verbose_name='Valor do ponto')),
            ],
        ),
        migrations.CreateModel(
            name='Selic',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ano', models.CharField(max_length=4, verbose_name='Ano')),
                ('janeiro', models.FloatField()),
                ('fevereiro', models.FloatField()),
                ('marco', models.FloatField()),
                ('abril', models.FloatField()),
                ('maio', models.FloatField()),
                ('junho', models.FloatField()),
                ('julho', models.FloatField()),
                ('agosto', models.FloatField()),
                ('setembro', models.FloatField()),
                ('outubro', models.FloatField()),
                ('novembro', models.FloatField()),
                ('dezembro', models.FloatField()),
            ],
        ),
        migrations.AlterField(
            model_name='cargoemprego',
            name='codcargo',
            field=models.CharField(max_length=10, verbose_name='Código'),
        ),
        migrations.AlterField(
            model_name='cargoemprego',
            name='codgrupocargo',
            field=models.CharField(max_length=10, verbose_name='Grupo'),
        ),
        migrations.AlterField(
            model_name='cargoemprego',
            name='nivel',
            field=models.CharField(max_length=10, verbose_name='Nível'),
        ),
        migrations.AlterField(
            model_name='cargoemprego',
            name='nomecargo',
            field=models.CharField(max_length=200, verbose_name='Nome'),
        ),
        migrations.AlterField(
            model_name='orgaosiape',
            name='codigo',
            field=models.CharField(max_length=10, verbose_name='Código'),
        ),
        migrations.AlterField(
            model_name='orgaosiape',
            name='nome',
            field=models.CharField(max_length=200, verbose_name='Nome'),
        ),
        migrations.AlterField(
            model_name='rubricas',
            name='codigorubrica',
            field=models.CharField(max_length=10, verbose_name='Código'),
        ),
        migrations.AlterField(
            model_name='rubricas',
            name='nomerubrica',
            field=models.CharField(max_length=200, verbose_name='Rubrica'),
        ),
    ]
