# Generated by Django 3.1.3 on 2021-02-25 16:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('acd_lst', '0007_auto_20210224_1901'),
    ]

    operations = [
        migrations.AlterField(
            model_name='selic',
            name='abril',
            field=models.DecimalField(decimal_places=4, max_digits=4, verbose_name='Abril'),
        ),
        migrations.AlterField(
            model_name='selic',
            name='agosto',
            field=models.DecimalField(decimal_places=4, max_digits=4, verbose_name='Agosto'),
        ),
        migrations.AlterField(
            model_name='selic',
            name='dezembro',
            field=models.DecimalField(decimal_places=4, max_digits=4, verbose_name='Dezembro'),
        ),
        migrations.AlterField(
            model_name='selic',
            name='fevereiro',
            field=models.DecimalField(decimal_places=4, max_digits=4, verbose_name='Fevereiro'),
        ),
        migrations.AlterField(
            model_name='selic',
            name='janeiro',
            field=models.DecimalField(decimal_places=4, max_digits=4, verbose_name='Janeiro'),
        ),
        migrations.AlterField(
            model_name='selic',
            name='julho',
            field=models.DecimalField(decimal_places=4, max_digits=4, verbose_name='Julho'),
        ),
        migrations.AlterField(
            model_name='selic',
            name='junho',
            field=models.DecimalField(decimal_places=4, max_digits=4, verbose_name='Junho'),
        ),
        migrations.AlterField(
            model_name='selic',
            name='maio',
            field=models.DecimalField(decimal_places=4, max_digits=4, verbose_name='Maio'),
        ),
        migrations.AlterField(
            model_name='selic',
            name='marco',
            field=models.DecimalField(decimal_places=4, max_digits=4, verbose_name='Março'),
        ),
        migrations.AlterField(
            model_name='selic',
            name='novembro',
            field=models.DecimalField(decimal_places=4, max_digits=4, verbose_name='Novembro'),
        ),
        migrations.AlterField(
            model_name='selic',
            name='outubro',
            field=models.DecimalField(decimal_places=4, max_digits=4, verbose_name='Outubro'),
        ),
        migrations.AlterField(
            model_name='selic',
            name='setembro',
            field=models.DecimalField(decimal_places=4, max_digits=4, verbose_name='Setembro'),
        ),
    ]
