# Generated by Django 4.2 on 2023-04-28 12:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('acd_lst', '0008_auto_20210225_1310'),
    ]

    operations = [
        migrations.CreateModel(
            name='T01TabelaDCP',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('t01_data', models.DateTimeField(blank=True, db_column='T01_DATA', null=True, verbose_name='DATA')),
                ('t01_cod_indexador', models.CharField(blank=True, db_column='T01_INDEXADOR', max_length=20, null=True, verbose_name='INDEXADOR')),
                ('t01_var_per_mensal', models.DecimalField(blank=True, db_column='T01_VAR_PER_MENSAL', decimal_places=10, max_digits=18, null=True, verbose_name='VAR PERC MENSAL')),
                ('t01_num_indice_var_mensal', models.DecimalField(blank=True, db_column='T01_NUM_INDICE_VAR_MENSAL', decimal_places=10, max_digits=18, null=True, verbose_name='NUM ÍNDICE VAR MENSAL')),
                ('t01_fator_vigente', models.DecimalField(blank=True, db_column='T01_FATOR_VIGENTE', decimal_places=10, max_digits=18, null=True, verbose_name='FATOR VIGENTE')),
                ('t01_indice_correcao', models.DecimalField(blank=True, db_column='T01_INDICE_CORRECAO', decimal_places=10, max_digits=18, null=True, verbose_name='INDICE CORREÇÃO')),
            ],
            options={
                'verbose_name_plural': '1. Tabela c.m. cond. geral IPCA-e',
                'ordering': ['t01_data'],
            },
        ),
        migrations.CreateModel(
            name='T02TabelaDCP',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('t02_data', models.DateTimeField(blank=True, db_column='T02_DATA', null=True, verbose_name='DATA')),
                ('t02_cod_indexador', models.CharField(blank=True, db_column='T02_INDEXADOR', max_length=20, null=True, verbose_name='INDEXADOR')),
                ('t02_var_per_mensal', models.DecimalField(blank=True, db_column='T02_VAR_PER_MENSAL', decimal_places=10, max_digits=18, null=True, verbose_name='VAR PERC MENSAL')),
                ('t02_num_indice_var_mensal', models.DecimalField(blank=True, db_column='T02_NUM_INDICE_VAR_MENSAL', decimal_places=10, max_digits=18, null=True, verbose_name='NUM ÍNDICE VAR MENSAL')),
                ('t02_fator_vigente', models.DecimalField(blank=True, db_column='T02_FATOR_VIGENTE', decimal_places=10, max_digits=18, null=True, verbose_name='FATOR VIGENTE')),
                ('t02_indice_correcao', models.DecimalField(blank=True, db_column='T02_INDICE_CORRECAO', decimal_places=10, max_digits=18, null=True, verbose_name='INDICE CORREÇÃO')),
            ],
            options={
                'verbose_name_plural': '2. Tabela IPCA-e + SELIC 2003-2009',
                'ordering': ['t02_data'],
            },
        ),
        migrations.CreateModel(
            name='T03TabelaDCP',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('t03_data', models.DateTimeField(blank=True, db_column='T03_DATA', null=True, verbose_name='DATA')),
                ('t03_cod_indexador', models.CharField(blank=True, db_column='T03_INDEXADOR', max_length=20, null=True, verbose_name='INDEXADOR')),
                ('t03_var_per_mensal', models.DecimalField(blank=True, db_column='T03_VAR_PER_MENSAL', decimal_places=10, max_digits=18, null=True, verbose_name='VAR PERC MENSAL')),
                ('t03_num_indice_var_mensal', models.DecimalField(blank=True, db_column='T03_NUM_INDICE_VAR_MENSAL', decimal_places=10, max_digits=18, null=True, verbose_name='NUM ÍNDICE VAR MENSAL')),
                ('t03_fator_vigente', models.DecimalField(blank=True, db_column='T03_FATOR_VIGENTE', decimal_places=10, max_digits=18, null=True, verbose_name='FATOR VIGENTE')),
                ('t03_indice_correcao', models.DecimalField(blank=True, db_column='T03_INDICE_CORRECAO', decimal_places=10, max_digits=18, null=True, verbose_name='INDICE CORREÇÃO')),
            ],
            options={
                'verbose_name_plural': '3. Tabela TR até mar2015',
                'ordering': ['t03_data'],
            },
        ),
        migrations.CreateModel(
            name='T04TabelaDCP',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('t04_data', models.DateTimeField(blank=True, db_column='T04_DATA', null=True, verbose_name='DATA')),
                ('t04_cod_indexador', models.CharField(blank=True, db_column='T04_INDEXADOR', max_length=20, null=True, verbose_name='INDEXADOR')),
                ('t04_var_per_mensal', models.DecimalField(blank=True, db_column='T04_VAR_PER_MENSAL', decimal_places=10, max_digits=18, null=True, verbose_name='VAR PERC MENSAL')),
                ('t04_num_indice_var_mensal', models.DecimalField(blank=True, db_column='T04_NUM_INDICE_VAR_MENSAL', decimal_places=10, max_digits=18, null=True, verbose_name='NUM ÍNDICE VAR MENSAL')),
                ('t04_fator_vigente', models.DecimalField(blank=True, db_column='T04_FATOR_VIGENTE', decimal_places=10, max_digits=18, null=True, verbose_name='FATOR VIGENTE')),
                ('t04_indice_correcao', models.DecimalField(blank=True, db_column='T04_INDICE_CORRECAO', decimal_places=10, max_digits=18, null=True, verbose_name='INDICE CORREÇÃO')),
            ],
            options={
                'verbose_name_plural': '4. Tabela TR até mar2015 + SELIC 2003-2009',
                'ordering': ['t04_data'],
            },
        ),
        migrations.CreateModel(
            name='T05TabelaDCP',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('t05_data', models.DateTimeField(blank=True, db_column='T05_DATA', null=True, verbose_name='DATA')),
                ('t05_cod_indexador', models.CharField(blank=True, db_column='T05_INDEXADOR', max_length=20, null=True, verbose_name='INDEXADOR')),
                ('t05_var_per_mensal', models.DecimalField(blank=True, db_column='T05_VAR_PER_MENSAL', decimal_places=10, max_digits=18, null=True, verbose_name='VAR PERC MENSAL')),
                ('t05_num_indice_var_mensal', models.DecimalField(blank=True, db_column='T05_NUM_INDICE_VAR_MENSAL', decimal_places=10, max_digits=18, null=True, verbose_name='NUM ÍNDICE VAR MENSAL')),
                ('t05_fator_vigente', models.DecimalField(blank=True, db_column='T05_FATOR_VIGENTE', decimal_places=10, max_digits=18, null=True, verbose_name='FATOR VIGENTE')),
                ('t05_indice_correcao', models.DecimalField(blank=True, db_column='T05_INDICE_CORRECAO', decimal_places=10, max_digits=18, null=True, verbose_name='INDICE CORREÇÃO')),
            ],
            options={
                'verbose_name_plural': '5. Tabela c.m. TR jul2009 em diante',
                'ordering': ['t05_data'],
            },
        ),
        migrations.CreateModel(
            name='T06TabelaDCP',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('t06_data', models.DateTimeField(blank=True, db_column='T06_DATA', null=True, verbose_name='DATA')),
                ('t06_cod_indexador', models.CharField(blank=True, db_column='T06_INDEXADOR', max_length=20, null=True, verbose_name='INDEXADOR')),
                ('t06_var_per_mensal', models.DecimalField(blank=True, db_column='T06_VAR_PER_MENSAL', decimal_places=10, max_digits=18, null=True, verbose_name='VAR PERC MENSAL')),
                ('t06_num_indice_var_mensal', models.DecimalField(blank=True, db_column='T06_NUM_INDICE_VAR_MENSAL', decimal_places=10, max_digits=18, null=True, verbose_name='NUM ÍNDICE VAR MENSAL')),
                ('t06_fator_vigente', models.DecimalField(blank=True, db_column='T06_FATOR_VIGENTE', decimal_places=10, max_digits=18, null=True, verbose_name='FATOR VIGENTE')),
                ('t06_indice_correcao', models.DecimalField(blank=True, db_column='T06_INDICE_CORRECAO', decimal_places=10, max_digits=18, null=True, verbose_name='INDICE CORREÇÃO')),
            ],
            options={
                'verbose_name_plural': '6. Tabela TR + SELIC 2003-2009',
                'ordering': ['t06_data'],
            },
        ),
        migrations.CreateModel(
            name='T07TabelaDCP',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('t07_data', models.DateTimeField(blank=True, db_column='T07_DATA', null=True, verbose_name='DATA')),
                ('t07_cod_indexador', models.CharField(blank=True, db_column='T07_INDEXADOR', max_length=20, null=True, verbose_name='INDEXADOR')),
                ('t07_var_per_mensal', models.DecimalField(blank=True, db_column='T07_VAR_PER_MENSAL', decimal_places=10, max_digits=18, null=True, verbose_name='VAR PERC MENSAL')),
                ('t07_num_indice_var_mensal', models.DecimalField(blank=True, db_column='T07_NUM_INDICE_VAR_MENSAL', decimal_places=10, max_digits=18, null=True, verbose_name='NUM ÍNDICE VAR MENSAL')),
                ('t07_fator_vigente', models.DecimalField(blank=True, db_column='T07_FATOR_VIGENTE', decimal_places=10, max_digits=18, null=True, verbose_name='FATOR VIGENTE')),
                ('t07_indice_correcao', models.DecimalField(blank=True, db_column='T07_INDICE_CORRECAO', decimal_places=10, max_digits=18, null=True, verbose_name='INDICE CORREÇÃO')),
            ],
            options={
                'verbose_name_plural': '7. Tabela c.m. cond. geral TR set2017',
                'ordering': ['t07_data'],
            },
        ),
        migrations.CreateModel(
            name='T08TabelaDCP',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('t08_data', models.DateTimeField(blank=True, db_column='T08_DATA', null=True, verbose_name='DATA')),
                ('t08_cod_indexador', models.CharField(blank=True, db_column='T08_INDEXADOR', max_length=20, null=True, verbose_name='INDEXADOR')),
                ('t08_var_per_mensal', models.DecimalField(blank=True, db_column='T08_VAR_PER_MENSAL', decimal_places=10, max_digits=18, null=True, verbose_name='VAR PERC MENSAL')),
                ('t08_num_indice_var_mensal', models.DecimalField(blank=True, db_column='T08_NUM_INDICE_VAR_MENSAL', decimal_places=10, max_digits=18, null=True, verbose_name='NUM ÍNDICE VAR MENSAL')),
                ('t08_fator_vigente', models.DecimalField(blank=True, db_column='T08_FATOR_VIGENTE', decimal_places=10, max_digits=18, null=True, verbose_name='FATOR VIGENTE')),
                ('t08_indice_correcao', models.DecimalField(blank=True, db_column='T08_INDICE_CORRECAO', decimal_places=10, max_digits=18, null=True, verbose_name='INDICE CORREÇÃO')),
            ],
            options={
                'verbose_name_plural': '8. TR até set2017 + SELIC 2003-2009',
                'ordering': ['t08_data'],
            },
        ),
        migrations.CreateModel(
            name='T09TabelaDCP',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('t09_data', models.DateTimeField(blank=True, db_column='T09_DATA', null=True, verbose_name='DATA')),
                ('t09_cod_indexador', models.CharField(blank=True, db_column='T09_INDEXADOR', max_length=20, null=True, verbose_name='INDEXADOR')),
                ('t09_var_per_mensal', models.DecimalField(blank=True, db_column='T09_VAR_PER_MENSAL', decimal_places=10, max_digits=18, null=True, verbose_name='VAR PERC MENSAL')),
                ('t09_num_indice_var_mensal', models.DecimalField(blank=True, db_column='T09_NUM_INDICE_VAR_MENSAL', decimal_places=10, max_digits=18, null=True, verbose_name='NUM ÍNDICE VAR MENSAL')),
                ('t09_fator_vigente', models.DecimalField(blank=True, db_column='T09_FATOR_VIGENTE', decimal_places=10, max_digits=18, null=True, verbose_name='FATOR VIGENTE')),
                ('t09_indice_correcao', models.DecimalField(blank=True, db_column='T09_INDICE_CORRECAO', decimal_places=10, max_digits=18, null=True, verbose_name='INDICE CORREÇÃO')),
            ],
            options={
                'verbose_name_plural': '9. TR dez2013 IPCA-e jan2014',
                'ordering': ['t09_data'],
            },
        ),
        migrations.CreateModel(
            name='T10TabelaDCP',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('t10_data', models.DateTimeField(blank=True, db_column='T10_DATA', null=True, verbose_name='DATA')),
                ('t10_cod_indexador', models.CharField(blank=True, db_column='T10_INDEXADOR', max_length=20, null=True, verbose_name='INDEXADOR')),
                ('t10_var_per_mensal', models.DecimalField(blank=True, db_column='T10_VAR_PER_MENSAL', decimal_places=10, max_digits=18, null=True, verbose_name='VAR PERC MENSAL')),
                ('t10_num_indice_var_mensal', models.DecimalField(blank=True, db_column='T10_NUM_INDICE_VAR_MENSAL', decimal_places=10, max_digits=18, null=True, verbose_name='NUM ÍNDICE VAR MENSAL')),
                ('t10_fator_vigente', models.DecimalField(blank=True, db_column='T10_FATOR_VIGENTE', decimal_places=10, max_digits=18, null=True, verbose_name='FATOR VIGENTE')),
                ('t10_indice_correcao', models.DecimalField(blank=True, db_column='T10_INDICE_CORRECAO', decimal_places=10, max_digits=18, null=True, verbose_name='INDICE CORREÇÃO')),
            ],
            options={
                'verbose_name_plural': '10. TR dez2013 IPCA-e jan2014-SELIC',
                'ordering': ['t10_data'],
            },
        ),
        migrations.CreateModel(
            name='T11TabelaDCP',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('t11_data', models.DateTimeField(blank=True, db_column='T11_DATA', null=True, verbose_name='DATA')),
                ('t11_cod_indexador', models.CharField(blank=True, db_column='T11_INDEXADOR', max_length=20, null=True, verbose_name='INDEXADOR')),
                ('t11_var_per_mensal', models.DecimalField(blank=True, db_column='T11_VAR_PER_MENSAL', decimal_places=10, max_digits=18, null=True, verbose_name='VAR PERC MENSAL')),
                ('t11_num_indice_var_mensal', models.DecimalField(blank=True, db_column='T11_NUM_INDICE_VAR_MENSAL', decimal_places=10, max_digits=18, null=True, verbose_name='NUM ÍNDICE VAR MENSAL')),
                ('t11_fator_vigente', models.DecimalField(blank=True, db_column='T11_FATOR_VIGENTE', decimal_places=10, max_digits=18, null=True, verbose_name='FATOR VIGENTE')),
                ('t11_indice_correcao', models.DecimalField(blank=True, db_column='T11_INDICE_CORRECAO', decimal_places=10, max_digits=18, null=True, verbose_name='INDICE CORREÇÃO')),
            ],
            options={
                'verbose_name_plural': '11. Tabela c.m. desapropriação',
                'ordering': ['t11_data'],
            },
        ),
        migrations.CreateModel(
            name='T12TabelaDCP',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('t12_data', models.DateTimeField(blank=True, db_column='T12_DATA', null=True, verbose_name='DATA')),
                ('t12_cod_indexador', models.CharField(blank=True, db_column='T12_INDEXADOR', max_length=20, null=True, verbose_name='INDEXADOR')),
                ('t12_var_per_mensal', models.DecimalField(blank=True, db_column='T12_VAR_PER_MENSAL', decimal_places=10, max_digits=18, null=True, verbose_name='VAR PERC MENSAL')),
                ('t12_num_indice_var_mensal', models.DecimalField(blank=True, db_column='T12_NUM_INDICE_VAR_MENSAL', decimal_places=10, max_digits=18, null=True, verbose_name='NUM ÍNDICE VAR MENSAL')),
                ('t12_fator_vigente', models.DecimalField(blank=True, db_column='T12_FATOR_VIGENTE', decimal_places=10, max_digits=18, null=True, verbose_name='FATOR VIGENTE')),
                ('t12_indice_correcao', models.DecimalField(blank=True, db_column='T12_INDICE_CORRECAO', decimal_places=10, max_digits=18, null=True, verbose_name='INDICE CORREÇÃO')),
            ],
            options={
                'verbose_name_plural': '12. Tabela c.m. benef. INPC',
                'ordering': ['t12_data'],
            },
        ),
        migrations.CreateModel(
            name='T13TabelaDCP',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('t13_data', models.DateTimeField(blank=True, db_column='T13_DATA', null=True, verbose_name='DATA')),
                ('t13_cod_indexador', models.CharField(blank=True, db_column='T13_INDEXADOR', max_length=20, null=True, verbose_name='INDEXADOR')),
                ('t13_var_per_mensal', models.DecimalField(blank=True, db_column='T13_VAR_PER_MENSAL', decimal_places=10, max_digits=18, null=True, verbose_name='VAR PERC MENSAL')),
                ('t13_num_indice_var_mensal', models.DecimalField(blank=True, db_column='T13_NUM_INDICE_VAR_MENSAL', decimal_places=10, max_digits=18, null=True, verbose_name='NUM ÍNDICE VAR MENSAL')),
                ('t13_fator_vigente', models.DecimalField(blank=True, db_column='T13_FATOR_VIGENTE', decimal_places=10, max_digits=18, null=True, verbose_name='FATOR VIGENTE')),
                ('t13_indice_correcao', models.DecimalField(blank=True, db_column='T13_INDICE_CORRECAO', decimal_places=10, max_digits=18, null=True, verbose_name='INDICE CORREÇÃO')),
            ],
            options={
                'verbose_name_plural': '13. Tabela c.m. benef. TR mar2015',
                'ordering': ['t13_data'],
            },
        ),
        migrations.CreateModel(
            name='T14TabelaDCP',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('t14_data', models.DateTimeField(blank=True, db_column='T14_DATA', null=True, verbose_name='DATA')),
                ('t14_cod_indexador', models.CharField(blank=True, db_column='T14_INDEXADOR', max_length=20, null=True, verbose_name='INDEXADOR')),
                ('t14_var_per_mensal', models.DecimalField(blank=True, db_column='T14_VAR_PER_MENSAL', decimal_places=10, max_digits=18, null=True, verbose_name='VAR PERC MENSAL')),
                ('t14_num_indice_var_mensal', models.DecimalField(blank=True, db_column='T14_NUM_INDICE_VAR_MENSAL', decimal_places=10, max_digits=18, null=True, verbose_name='NUM ÍNDICE VAR MENSAL')),
                ('t14_fator_vigente', models.DecimalField(blank=True, db_column='T14_FATOR_VIGENTE', decimal_places=10, max_digits=18, null=True, verbose_name='FATOR VIGENTE')),
                ('t14_indice_correcao', models.DecimalField(blank=True, db_column='T14_INDICE_CORRECAO', decimal_places=10, max_digits=18, null=True, verbose_name='INDICE CORREÇÃO')),
            ],
            options={
                'verbose_name_plural': '14. Trabalhista TR jul2009',
                'ordering': ['t14_data'],
            },
        ),
        migrations.CreateModel(
            name='T15TabelaDCP',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('t15_data', models.DateTimeField(blank=True, db_column='T15_DATA', null=True, verbose_name='DATA')),
                ('t15_cod_indexador', models.CharField(blank=True, db_column='T15_INDEXADOR', max_length=20, null=True, verbose_name='INDEXADOR')),
                ('t15_var_per_mensal', models.DecimalField(blank=True, db_column='T15_VAR_PER_MENSAL', decimal_places=10, max_digits=18, null=True, verbose_name='VAR PERC MENSAL')),
                ('t15_num_indice_var_mensal', models.DecimalField(blank=True, db_column='T15_NUM_INDICE_VAR_MENSAL', decimal_places=10, max_digits=18, null=True, verbose_name='NUM ÍNDICE VAR MENSAL')),
                ('t15_fator_vigente', models.DecimalField(blank=True, db_column='T15_FATOR_VIGENTE', decimal_places=10, max_digits=18, null=True, verbose_name='FATOR VIGENTE')),
                ('t15_indice_correcao', models.DecimalField(blank=True, db_column='T15_INDICE_CORRECAO', decimal_places=10, max_digits=18, null=True, verbose_name='INDICE CORREÇÃO')),
            ],
            options={
                'verbose_name_plural': '15. Trabalhista IPCA-e abr2015 a nov2017',
                'ordering': ['t15_data'],
            },
        ),
        migrations.CreateModel(
            name='T16TabelaDCP',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('t16_data', models.DateTimeField(blank=True, db_column='T16_DATA', null=True, verbose_name='DATA')),
                ('t16_cod_indexador', models.CharField(blank=True, db_column='T16_INDEXADOR', max_length=20, null=True, verbose_name='INDEXADOR')),
                ('t16_meta_selic', models.DecimalField(blank=True, db_column='T16_META_SELIC', decimal_places=10, max_digits=18, null=True, verbose_name='META SELIC COPOM')),
                ('t16_taxa_mensal', models.DecimalField(blank=True, db_column='T16_TAXA_MENSAL', decimal_places=10, max_digits=18, null=True, verbose_name='TAXA MENSAL')),
            ],
            options={
                'verbose_name_plural': '16. Juros Poupança',
                'ordering': ['t16_data'],
            },
        ),
        migrations.CreateModel(
            name='T17TabelaDCP',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('t17_data', models.DateTimeField(blank=True, db_column='T17_DATA', null=True, verbose_name='DATA')),
                ('t17_cod_indexador', models.CharField(blank=True, db_column='T17_INDEXADOR', max_length=20, null=True, verbose_name='INDEXADOR')),
                ('t17_x1', models.DecimalField(blank=True, db_column='T17_X1', decimal_places=10, max_digits=18, null=True, verbose_name='X1')),
                ('t17_x2', models.DecimalField(blank=True, db_column='T17_X2', decimal_places=10, max_digits=18, null=True, verbose_name='X2')),
                ('t17_x3', models.DecimalField(blank=True, db_column='T17_X3', decimal_places=10, max_digits=18, null=True, verbose_name='X3')),
                ('t17_x4', models.DecimalField(blank=True, db_column='T17_X4', decimal_places=10, max_digits=18, null=True, verbose_name='X4')),
                ('t17_x5', models.DecimalField(blank=True, db_column='T17_X5', decimal_places=10, max_digits=18, null=True, verbose_name='X5')),
            ],
            options={
                'verbose_name_plural': '17. Juros 0,5% \\até jun2009',
                'ordering': ['t17_data'],
            },
        ),
        migrations.CreateModel(
            name='T18TabelaDCP',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('t18_data', models.DateTimeField(blank=True, db_column='T17_DATA', null=True, verbose_name='DATA')),
                ('t18_cod_indexador', models.CharField(blank=True, db_column='T17_INDEXADOR', max_length=20, null=True, verbose_name='INDEXADOR')),
                ('t18_x1', models.DecimalField(blank=True, db_column='T18_X1', decimal_places=10, max_digits=18, null=True, verbose_name='X1')),
                ('t18_x2', models.DecimalField(blank=True, db_column='T18_X2', decimal_places=10, max_digits=18, null=True, verbose_name='X2')),
                ('t18_x3', models.DecimalField(blank=True, db_column='T18_X3', decimal_places=10, max_digits=18, null=True, verbose_name='X3')),
                ('t18_x4', models.DecimalField(blank=True, db_column='T18_X4', decimal_places=10, max_digits=18, null=True, verbose_name='X4')),
                ('t18_x5', models.DecimalField(blank=True, db_column='T18_X5', decimal_places=10, max_digits=18, null=True, verbose_name='X5')),
            ],
            options={
                'verbose_name_plural': '18. Juros 1% \\até jul2001',
                'ordering': ['t18_data'],
            },
        ),
        migrations.CreateModel(
            name='T19TabelaDCP',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('t19_data', models.DateTimeField(blank=True, db_column='T19_DATA', null=True, verbose_name='DATA')),
                ('t19_cod_indexador', models.CharField(blank=True, db_column='T19_INDEXADOR', max_length=20, null=True, verbose_name='INDEXADOR')),
                ('t19_indice_correcao', models.DecimalField(blank=True, db_column='T19_INDICE_CORRECAO', decimal_places=10, max_digits=18, null=True, verbose_name='INDICE CORREÇÃO')),
            ],
            options={
                'verbose_name_plural': '19. Média SELIC parcelamento',
                'ordering': ['t19_data'],
            },
        ),
        migrations.CreateModel(
            name='T20TabelaDCP',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('t20_ord', models.IntegerField(blank=True, db_column='T20_ORDEM', null=True, verbose_name='ORD')),
                ('t20_vigencia', models.CharField(blank=True, db_column='T20_VIGENCIA', max_length=30, null=True, verbose_name='VIGÊNCIA')),
                ('t20_moeda', models.CharField(blank=True, db_column='T20_MOEDA', max_length=30, null=True, verbose_name='MOEDA')),
                ('t20_alteracao', models.CharField(blank=True, db_column='T20_ALTERACAO', max_length=250, null=True, verbose_name='ALTERAÇÃO')),
                ('t20_legislacao', models.CharField(blank=True, db_column='T20_LEGISLACAO', max_length=250, null=True, verbose_name='LEGISLAÇÃO')),
            ],
            options={
                'verbose_name_plural': '20. Série histórica das moedas',
                'ordering': ['t20_ord'],
            },
        ),
        migrations.CreateModel(
            name='T21ListaTabelasDCP',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('t21_cod_tabela', models.IntegerField(blank=True, db_column='T21_CODIGO', null=True, verbose_name='CÓDIGO')),
                ('t21_nome_tabela', models.CharField(blank=True, db_column='T21_NOME_TABELA', max_length=50, null=True, verbose_name='NOME DA TABELA')),
                ('t21_obs_tabela', models.CharField(blank=True, db_column='T21_OBS_TABELA', max_length=1000, null=True, verbose_name='OBSERVAÇÕES')),
                ('t21_indexador', models.CharField(blank=True, db_column='T21_INDEXADOR', max_length=30, null=True, verbose_name='INDEXADOR')),
            ],
            options={
                'verbose_name': 'Tabelas-DCP',
                'verbose_name_plural': 'Tabelas-DCP',
                'ordering': ['t21_cod_tabela'],
            },
        ),
        migrations.CreateModel(
            name='T21TabelaDCP',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('t21_data', models.DateTimeField(blank=True, db_column='T21_DATA', null=True, verbose_name='DATA')),
                ('t21_cod_indexador', models.CharField(blank=True, db_column='T21_INDEXADOR', max_length=20, null=True, verbose_name='INDEXADOR')),
                ('t21_var_per_mensal', models.DecimalField(blank=True, db_column='T21_VAR_PER_MENSAL', decimal_places=10, max_digits=18, null=True, verbose_name='VAR PERC MENSAL')),
                ('t21_num_indice_var_mensal', models.DecimalField(blank=True, db_column='T21_NUM_INDICE_VAR_MENSAL', decimal_places=10, max_digits=18, null=True, verbose_name='NUM ÍNDICE VAR MENSAL')),
                ('t21_fator_vigente', models.DecimalField(blank=True, db_column='T21_FATOR_VIGENTE', decimal_places=10, max_digits=18, null=True, verbose_name='FATOR VIGENTE')),
                ('t21_indice_correcao', models.DecimalField(blank=True, db_column='T21_INDICE_CORRECAO', decimal_places=10, max_digits=18, null=True, verbose_name='INDICE CORREÇÃO')),
            ],
            options={
                'verbose_name_plural': '21. Tabela c.m. IPCA-e EC 113-2021',
                'ordering': ['t21_data'],
            },
        ),
        migrations.CreateModel(
            name='t22IndexadoresDCP',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('t03_cod_indexador', models.CharField(blank=True, db_column='T22_CODIGO', max_length=20, null=True)),
                ('t03_nome_indexador', models.CharField(blank=True, db_column='T22_NOME_INDEXADOR', max_length=50, null=True)),
                ('t03_descricao', models.CharField(blank=True, db_column='T22_DESCRICAO', max_length=70, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='T22TabelaDCP',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('t22_data', models.DateTimeField(blank=True, db_column='T22_DATA', null=True, verbose_name='DATA')),
                ('t22_cod_indexador', models.CharField(blank=True, db_column='T22_INDEXADOR', max_length=20, null=True, verbose_name='INDEXADOR')),
                ('t22_var_per_mensal', models.DecimalField(blank=True, db_column='T22_VAR_PER_MENSAL', decimal_places=10, max_digits=18, null=True, verbose_name='VAR PERC MENSAL')),
                ('t22_num_indice_var_mensal', models.DecimalField(blank=True, db_column='T22_NUM_INDICE_VAR_MENSAL', decimal_places=10, max_digits=18, null=True, verbose_name='NUM ÍNDICE VAR MENSAL')),
                ('t22_fator_vigente', models.DecimalField(blank=True, db_column='T22_FATOR_VIGENTE', decimal_places=10, max_digits=18, null=True, verbose_name='FATOR VIGENTE')),
                ('t22_indice_correcao', models.DecimalField(blank=True, db_column='T22_INDICE_CORRECAO', decimal_places=10, max_digits=18, null=True, verbose_name='INDICE CORREÇÃO')),
            ],
            options={
                'verbose_name_plural': '22. Tabela c.m. INPC',
                'ordering': ['t22_data'],
            },
        ),
        migrations.CreateModel(
            name='T23TabelaDCP',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('t23_data', models.DateTimeField(blank=True, db_column='T23_DATA', null=True, verbose_name='DATA')),
                ('t23_cod_indexador', models.CharField(blank=True, db_column='T23_INDEXADOR', max_length=20, null=True, verbose_name='INDEXADOR')),
                ('t23_var_per_mensal', models.DecimalField(blank=True, db_column='T23_VAR_PER_MENSAL', decimal_places=10, max_digits=18, null=True, verbose_name='VAR PERC MENSAL')),
                ('t23_num_indice_var_mensal', models.DecimalField(blank=True, db_column='T23_NUM_INDICE_VAR_MENSAL', decimal_places=10, max_digits=18, null=True, verbose_name='NUM ÍNDICE VAR MENSAL')),
                ('t23_fator_vigente', models.DecimalField(blank=True, db_column='T23_FATOR_VIGENTE', decimal_places=10, max_digits=18, null=True, verbose_name='FATOR VIGENTE')),
                ('t23_indice_correcao', models.DecimalField(blank=True, db_column='T23_INDICE_CORRECAO', decimal_places=10, max_digits=18, null=True, verbose_name='INDICE CORREÇÃO')),
            ],
            options={
                'verbose_name_plural': '23. Tabela c.m. INPC + IPCA-E',
                'ordering': ['t23_data'],
            },
        ),
        migrations.CreateModel(
            name='T24TabelaDCP',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('t24_data', models.DateTimeField(blank=True, db_column='T24_DATA', null=True, verbose_name='DATA')),
                ('t24_cod_indexador', models.CharField(blank=True, db_column='T24_INDEXADOR', max_length=20, null=True, verbose_name='INDEXADOR')),
                ('t24_fator_ipcae', models.DecimalField(blank=True, db_column='T24_FATOR_IPCAE', decimal_places=10, max_digits=18, null=True, verbose_name='FATOR IPCA-E')),
                ('t24_fator_tr', models.DecimalField(blank=True, db_column='T24_FATOR_TR', decimal_places=10, max_digits=18, null=True, verbose_name='FATOR TR')),
                ('t24_juros', models.DecimalField(blank=True, db_column='T24_JUROS', decimal_places=10, max_digits=18, null=True, verbose_name='JUROS')),
            ],
            options={
                'verbose_name_plural': '24. Tabela WebGCALC',
                'ordering': ['t24_data'],
            },
        ),
        migrations.DeleteModel(
            name='Selic',
        ),
        migrations.AlterModelOptions(
            name='cargoemprego',
            options={'verbose_name': 'Cargo-Emprego', 'verbose_name_plural': 'Cargo-Emprego'},
        ),
        migrations.AlterModelOptions(
            name='gratpontuacao',
            options={'verbose_name': 'Pontuação', 'verbose_name_plural': 'Pontuação'},
        ),
        migrations.AlterModelOptions(
            name='gratvalorponto',
            options={'verbose_name': 'Valor do Ponto', 'verbose_name_plural': 'Valor do Ponto'},
        ),
        migrations.AlterModelOptions(
            name='orgaosiape',
            options={'verbose_name': 'Órgão Siape', 'verbose_name_plural': 'Órgão Siape'},
        ),
        migrations.AlterModelOptions(
            name='rubricas',
            options={'verbose_name': 'Rubrica', 'verbose_name_plural': 'Rubricas'},
        ),
        migrations.AlterField(
            model_name='cargoemprego',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AlterField(
            model_name='gratpontuacao',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AlterField(
            model_name='gratpontuacao',
            name='nomegrat',
            field=models.CharField(choices=[('GDATA', 'GDATA'), ('GDPGTAS', 'GDPGTAS'), ('GDASST', 'GDASST'), ('GDPGPE', 'GDPGPE')], max_length=10, verbose_name='Gratificação'),
        ),
        migrations.AlterField(
            model_name='gratvalorponto',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AlterField(
            model_name='gratvalorponto',
            name='nomegrat',
            field=models.CharField(choices=[('GDATA', 'GDATA'), ('GDPGTAS', 'GDPGTAS'), ('GDASST', 'GDASST'), ('GDPGPE', 'GDPGPE')], max_length=10, verbose_name='Gratificação'),
        ),
        migrations.AlterField(
            model_name='list',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AlterField(
            model_name='orgaosiape',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AlterField(
            model_name='rubricas',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
    ]
