# Generated by Django 4.0 on 2023-07-15 23:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('acd_lst', '0009_t01tabeladcp_t02tabeladcp_t03tabeladcp_t04tabeladcp_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Document',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('description', models.CharField(blank=True, max_length=255)),
                ('document', models.FileField(upload_to='documents/')),
                ('uploaded_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.DeleteModel(
            name='Cargoemprego',
        ),
        migrations.DeleteModel(
            name='GratPontuacao',
        ),
        migrations.DeleteModel(
            name='GratValorPonto',
        ),
        migrations.DeleteModel(
            name='Orgaosiape',
        ),
        migrations.DeleteModel(
            name='Rubricas',
        ),
        migrations.DeleteModel(
            name='T01TabelaDCP',
        ),
        migrations.DeleteModel(
            name='T02TabelaDCP',
        ),
        migrations.DeleteModel(
            name='T03TabelaDCP',
        ),
        migrations.DeleteModel(
            name='T04TabelaDCP',
        ),
        migrations.DeleteModel(
            name='T05TabelaDCP',
        ),
        migrations.DeleteModel(
            name='T06TabelaDCP',
        ),
        migrations.DeleteModel(
            name='T07TabelaDCP',
        ),
        migrations.DeleteModel(
            name='T08TabelaDCP',
        ),
        migrations.DeleteModel(
            name='T09TabelaDCP',
        ),
        migrations.DeleteModel(
            name='T10TabelaDCP',
        ),
        migrations.DeleteModel(
            name='T11TabelaDCP',
        ),
        migrations.DeleteModel(
            name='T12TabelaDCP',
        ),
        migrations.DeleteModel(
            name='T13TabelaDCP',
        ),
        migrations.DeleteModel(
            name='T14TabelaDCP',
        ),
        migrations.DeleteModel(
            name='T15TabelaDCP',
        ),
        migrations.DeleteModel(
            name='T16TabelaDCP',
        ),
        migrations.DeleteModel(
            name='T17TabelaDCP',
        ),
        migrations.DeleteModel(
            name='T18TabelaDCP',
        ),
        migrations.DeleteModel(
            name='T19TabelaDCP',
        ),
        migrations.DeleteModel(
            name='T20TabelaDCP',
        ),
        migrations.DeleteModel(
            name='T21ListaTabelasDCP',
        ),
        migrations.DeleteModel(
            name='T21TabelaDCP',
        ),
        migrations.DeleteModel(
            name='t22IndexadoresDCP',
        ),
        migrations.DeleteModel(
            name='T22TabelaDCP',
        ),
        migrations.DeleteModel(
            name='T23TabelaDCP',
        ),
        migrations.DeleteModel(
            name='T24TabelaDCP',
        ),
    ]
