# Generated by Django 4.0 on 2025-02-04 19:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('acd_lst', '0010_document_delete_cargoemprego_delete_gratpontuacao_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='TbBase317',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('codigorubrica', models.CharField(max_length=10, verbose_name='Código')),
                ('nomerubrica', models.CharField(max_length=200, verbose_name='Rubrica')),
                ('tipo', models.CharField(max_length=1, verbose_name='Tipo')),
            ],
            options={
                'verbose_name': 'Base Cálculo 3.17',
                'verbose_name_plural': 'Base Cálculo 3.17',
            },
        ),
    ]
