# Generated by Django 4.0 on 2025-02-07 18:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('acd_lst', '0011_tbbase317'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='tbbase317',
            table='tb_base317',
        ),
    ]
