# Generated by Django 4.0 on 2025-02-07 18:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('acd_lst', '0012_alter_tbbase317_table'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tbbase317',
            name='codigorubrica',
            field=models.IntegerField(verbose_name='Código'),
        ),
    ]
