# Generated by Django 4.0 on 2025-02-27 20:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('acd_lst', '0013_alter_tbbase317_codigorubrica'),
    ]

    operations = [
        migrations.CreateModel(
            name='AbateTeto',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('codigorubrica', models.IntegerField(verbose_name='Código')),
                ('nomerubrica', models.CharField(max_length=200, verbose_name='Rubrica')),
                ('dtprimeirointervalo', models.CharField(max_length=1, verbose_name='Até janeiro 2004')),
                ('dtsegundointervalo', models.CharField(max_length=1, verbose_name='A partir fevereiro 2004')),
            ],
            options={
                'verbose_name': 'Base Cálculo Abate Teto',
                'verbose_name_plural': 'Base Cálculo Abate Teto',
                'db_table': 'tb_abateteto',
            },
        ),
    ]
