# Generated by Django 4.0 on 2025-03-08 20:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('acd_lst', '0014_abateteto'),
    ]

    operations = [
        migrations.CreateModel(
            name='TbBase2886',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('codigorubrica', models.IntegerField(verbose_name='Código')),
                ('nomerubrica', models.CharField(max_length=200, verbose_name='Rubrica')),
                ('tipo', models.CharField(max_length=1, verbose_name='Tipo')),
            ],
            options={
                'verbose_name': 'Base Cálculo 28.86',
                'verbose_name_plural': 'Base Cálculo 28.86',
                'db_table': 'tb_base2886',
            },
        ),
    ]
